{
    "apps": [
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "07a71636f9c8854049d37fccdbecec10", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.3"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "49d5b1e977c6f353e6b65f6bd5590af2", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.1"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "a3c8d1175766f096771a9792e12dee2e", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "aria2", 
            "version": "2.2"
        }, 
        {
            "build_date": "2021-04-06_22:53:01", 
            "changelog": "", 
            "description": "CloudFlare DDNS", 
            "home_url": "Module_cfddns.asp", 
            "md5": "22787d38793de1f9377c3467ef4c77fb", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "CloudFlare DDNS", 
            "version": "1.0"
        }, 
        {
            "build_date": "2021-04-06_22:53:03", 
            "changelog": "", 
            "description": "ddnspod", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "bd5d4930d8cc53e783b34a49cd971d7a", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "ddnspod", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-04-06_22:53:03", 
            "changelog": "", 
            "description": "ddnsto内网穿透", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "5f27da1297000c2ed3bf30bf19172f1d", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "ddnsto", 
            "version": "2.2"
        }, 
        {
            "build_date": "2021-04-06_22:53:01", 
            "changelog": "", 
            "description": "易有云 （EasyExplorer） 跨平台文件同步，支持双向同步！", 
            "home_url": "Module_easyexplorer.asp", 
            "md5": "262233f9fa0cd9f95693b61657a375ae", 
            "name": "easyexplorer", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "易有云", 
            "version": "2.4.1"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "迅雷快鸟，上网必备神器", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "4cf7462356a381f8e63b8b279c18aa0a", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "1.6"
        }, 
        {
            "build_date": "2021-06-21_09:29:54", 
            "changelog": "", 
            "description": "支持多种协议的内网穿透软件", 
            "home_url": "Module_frpc.asp", 
            "md5": "84bfe7d79a9550f56d04b8b0ec23abbb", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc内网穿透", 
            "version": "1.7"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "2a0ea28296947f7b069c4a738348ec79", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "1.5.2"
        }, 
        {
            "build_date": "2021-04-06_22:53:01", 
            "changelog": "", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "3fd4997455ea31f2ef9fd2eeb5dc1e92", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "1.6"
        }, 
        {
            "build_date": "2021-04-06_22:53:03", 
            "changelog": "", 
            "description": "KP: Kids Protect，互联网内容过滤，保护未成年人上网~", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "64678311abd70fd80d25030b563146f7", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "KidsProtect", 
            "version": "3.8.4.1"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "7d7079e3a1e3d1e0a4d3f7fe83ea4c1f", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.3"
        }, 
        {
            "build_date": "2021-07-15_17:25:50", 
            "changelog": "", 
            "description": "帮助RAX80刷回网件原厂固件，修复RAX80网件原厂分区", 
            "home_url": "Module_ngfix.asp", 
            "md5": "bb7e23991067127016f79bea3880e2de", 
            "name": "ngfix", 
            "port": "", 
            "server": "", 
            "tar_url": "ngfix/ngfix.tar.gz", 
            "title": "RAX80 Toolbox", 
            "version": "1.4"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "通过pushplus将路由器状态推送到微信上", 
            "home_url": "Module_pushplus.asp", 
            "md5": "00141477111e51cd4672a9325d76e59d", 
            "name": "pushplus", 
            "tar_url": "pushplus/pushplus.tar.gz", 
            "title": "pushplus全能推送", 
            "version": "0.4"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "自动签到", 
            "home_url": "Module_qiandao.asp", 
            "md5": "4f1f001781b9ae6fe1835fe0daad9715", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "自动签到", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-04-06_22:53:03", 
            "changelog": "", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "ffa9ebdf1aa1a517e393e2e77a28646a", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.6"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "一些小功能的插件", 
            "home_url": "Module_rog.asp", 
            "md5": "7f4dfa9df257cb349d521befb5dba119", 
            "name": "rog", 
            "tar_url": "rog/rog.tar.gz", 
            "title": "ROG工具箱", 
            "version": "4.2"
        }, 
        {
            "build_date": "2021-04-06_22:53:02", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_routerhook.asp", 
            "md5": "de9098952249a2cd8f1bce41124f5bcd", 
            "name": "routerhook", 
            "tar_url": "routerhook/routerhook.tar.gz", 
            "title": "RouterHook事件回调", 
            "version": "1.2"
        }, 
        {
            "build_date": "2021-04-06_22:53:01", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "d58db0a08fdd07321d399cac64e93a34", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "serverChan微信推送", 
            "version": "1.4.1"
        }, 
        {
            "build_date": "2021-04-06_22:53:01", 
            "changelog": "", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "b99d68755173c07c0eec689e50807a10", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "1.6"
        }, 
        {
            "build_date": "2021-04-06_22:53:01", 
            "changelog": "", 
            "description": "上海电信IPTV，4K IPTV 一键开启", 
            "home_url": "Module_shiptv.asp", 
            "md5": "7578e05571e4a50b00fccef6ec41b1ee", 
            "name": "shiptv", 
            "tar_url": "shiptv/shiptv.tar.gz", 
            "title": "上海电信IPTV", 
            "version": "1.1"
        }, 
        {
            "build_date": "2021-04-06_22:53:01", 
            "changelog": "", 
            "description": "VPN全家桶, ver 4.29 build 9680", 
            "home_url": "Module_softether.asp", 
            "md5": "0d998bafec7cc741b9e4a9e20494ed07", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "1.9"
        }, 
        {
            "build_date": "2021-04-06_22:53:03", 
            "changelog": "", 
            "description": "让路由器运行更稳定~", 
            "home_url": "Module_swap.asp", 
            "md5": "9dfa21fff3259a84600e7f09dfe4fcbf", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.7"
        }, 
        {
            "build_date": "2021-04-10_23:11:31", 
            "changelog": "", 
            "description": "使用U盘轻松挂载jffs", 
            "home_url": "Module_usb2jffs.asp", 
            "md5": "cc3bbc969a60d164898f5a30f65f872c", 
            "name": "usb2jffs", 
            "tar_url": "usb2jffs/usb2jffs.tar.gz", 
            "title": "USB2JFFS", 
            "version": "1.9.5"
        }, 
        {
            "build_date": "2021-04-22_22:23:58", 
            "changelog": "", 
            "description": "wifi boost: 路由器WiFi功率增强，增加信号覆盖范围。", 
            "home_url": "Module_wifiboost.asp", 
            "md5": "cf697f996026adbc81bb6fdfbd63eae4", 
            "name": "wifiboost", 
            "port": "8083", 
            "server": "42.192.18.234", 
            "tar_url": "wifiboost/wifiboost.tar.gz", 
            "title": "wifi boost", 
            "version": "4.0"
        }, 
        {
            "build_date": "2021-04-08_20:48:57", 
            "changelog": "", 
            "description": "ZeroTier 内网穿透", 
            "home_url": "Module_zerotier.asp", 
            "md5": "e95418ee07254116f78c5a2e1d45d7c4", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "ZeroTier", 
            "version": "1.3.8"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "e45a9e7ccdf2aef3318681e6b48460f3", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.7.2"
}