{
    "apps": [
        {
            "build_date": "2020-04-04_23:12:16", 
            "changelog": "", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "953432f700d62ee7706ec463adcbfe9d", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.0"
        }, 
        {
            "build_date": "2020-04-12_10:59:33", 
            "changelog": "", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "50c986a86edd72add608d5f6313a44bd", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.0"
        }, 
        {
            "build_date": "2020-04-12_16:42:24", 
            "changelog": "", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "71e34f2854d47071ad38d4af361d8f9f", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "aria2", 
            "version": "2.2"
        }, 
        {
            "build_date": "2020-04-12_16:42:28", 
            "changelog": "", 
            "description": "CloudFlare DDNS", 
            "home_url": "Module_cfddns.asp", 
            "md5": "6f4d6d5dc6cdf57e7c502e606222cd08", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "CloudFlare DDNS", 
            "version": "1.0"
        }, 
        {
            "build_date": "2020-04-12_16:42:34", 
            "changelog": "", 
            "description": "ddnspod", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "25755c3c4a36eebf093e1abee077f95b", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "ddnspod", 
            "version": "1.5"
        }, 
        {
            "build_date": "2020-04-12_16:42:38", 
            "changelog": "", 
            "description": "ddnsto内网穿透", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "486d63a02ea94a57f9ecb500873fc3c6", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "ddnsto", 
            "version": "2.0"
        }, 
        {
            "build_date": "2020-04-12_16:56:24", 
            "changelog": "", 
            "description": "易有云 （EasyExplorer） 跨平台文件同步，支持双向同步！", 
            "home_url": "Module_easyexplorer.asp", 
            "md5": "346556aa7d593dbcfc6f4bef97a0dcd8", 
            "name": "easyexplorer", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "易有云", 
            "version": "2.4"
        }, 
        {
            "build_date": "2020-04-12_16:56:29", 
            "changelog": "", 
            "description": "迅雷快鸟，上网必备神器", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "c42d32599a6a188bfeca9d13187dabde", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "1.6"
        }, 
        {
            "build_date": "2020-04-12_17:16:55", 
            "changelog": "", 
            "description": "支持多种协议的内网穿透软件", 
            "home_url": "Module_frpc.asp", 
            "md5": "980ea1bc3e8888ed94657928f28dd8fc", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc内网穿透", 
            "version": "1.6"
        }, 
        {
            "build_date": "2020-04-12_17:16:59", 
            "changelog": "", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "b846de637f3381ad4279ec3ee5c639fc", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "1.5"
        }, 
        {
            "build_date": "2020-04-12_17:17:06", 
            "changelog": "", 
            "description": "KP: Kids Protect，互联网内容过滤，保护未成年人上网~", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "d6b084f7fdf3ee81c481044f0b1ecfaa", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "KidsProtect", 
            "version": "3.8.4.1"
        }, 
        {
            "build_date": "2020-04-12_17:17:11", 
            "changelog": "", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "742b2358d448a690a3c6d4616a909e77", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.3"
        }, 
        {
            "build_date": "2020-04-12_17:17:16", 
            "changelog": "", 
            "description": "自动签到", 
            "home_url": "Module_qiandao.asp", 
            "md5": "582cbc0debd8fa028e8d042c5ab4847a", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "自动签到", 
            "version": "1.5"
        }, 
        {
            "build_date": "2020-04-12_17:17:19", 
            "changelog": "", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "90a279565d8acf12406c1eba70a1c37f", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.6"
        }, 
        {
            "build_date": "2020-04-12_11:25:50", 
            "changelog": "", 
            "description": "一些小功能的插件", 
            "home_url": "Module_rog.asp", 
            "md5": "00fe9215d75424fb2fb828ccf31a608c", 
            "name": "rog", 
            "tar_url": "rog/rog.tar.gz", 
            "title": "ROG工具箱", 
            "version": "2.7"
        }, 
        {
            "build_date": "2020-04-03_22:58:05", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_routerhook.asp", 
            "md5": "dfd49186fad844ff2e22d7ff93e2ca20", 
            "name": "routerhook", 
            "tar_url": "routerhook/routerhook.tar.gz", 
            "title": "RouterHook事件回调", 
            "version": "0.4"
        }, 
        {
            "build_date": "2020-03-26_16:28:18", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "aae829ef065d3da33c4ceac3ae4bb269", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "serverChan微信推送", 
            "version": "1.1"
        }, 
        {
            "build_date": "2019-07-10_22:31:15", 
            "changelog": "", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "c3c5d2809901054c2aa9857a23e34b03", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "1.5"
        }, 
        {
            "build_date": "2019-07-10_23:02:18", 
            "changelog": "", 
            "description": "VPN全家桶, ver 4.29 build 9680", 
            "home_url": "Module_softether.asp", 
            "md5": "87f7609abda0fd889bf15d879cadacf8", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "1.9"
        }, 
        {
            "build_date": "2018-12-04_21:57:04", 
            "changelog": "", 
            "description": "ss-server", 
            "home_url": "Module_ssserver.asp", 
            "md5": "da037cb6769a8b5289c173dfa1373179", 
            "name": "ssserver", 
            "tar_url": "ssserver/ssserver.tar.gz", 
            "title": "ss-server", 
            "version": "1.2"
        }, 
        {
            "build_date": "2020-04-05_21:35:45", 
            "changelog": "", 
            "description": "让路由器运行更稳定~", 
            "home_url": "Module_swap.asp", 
            "md5": "447311668a034e4b11367700415d94a3", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.0"
        }, 
        {
            "build_date": "2020-04-05_21:28:57", 
            "changelog": "", 
            "description": "轻松用U盘挂载jffs", 
            "home_url": "Module_usb2jffs.asp", 
            "md5": "f836b10804652929bf3b9327d97fed3d", 
            "name": "usb2jffs", 
            "tar_url": "usb2jffs/usb2jffs.tar.gz", 
            "title": "USB2JFFS", 
            "version": "1.6"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "1a1126e7a70393cbc1a49ed1e0a48f98", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.5.5"
}