{
    "apps": [
        {
            "author": "sadog",
            "build_date": "2021-08-20_22:31:29",
            "changelog": "",
            "description": "自动部署SSL证书",
            "home_url": "Module_acme.asp",
            "link": "https://github.com/acmesh-official/acme.sh",
            "md5": "37552b1bed88a0a43a05426b04d267ed",
            "name": "acme",
            "tags": "网络 安全",
            "tar_url": "acme/acme.tar.gz",
            "title": "Let's Encrypt",
            "version": "3.3"
        },
        {
            "author": "kyrios, sadog",
            "build_date": "2022-03-29_10:45:17",
            "changelog": "",
            "description": "aliddns",
            "home_url": "Module_aliddns.asp",
            "link": "",
            "md5": "20dec7108c4a49d4c3bb4e2e4b1af4e1",
            "name": "aliddns",
            "tags": "DDNS",
            "tar_url": "aliddns/aliddns.tar.gz",
            "title": "阿里DDNS",
            "version": "2.2"
        },
        {
            "author": "sadog",
            "build_date": "2025-11-03_00:07:36",
            "changelog": "",
            "description": "koolcenter/softcenter 一键来回切换！",
            "home_url": "Module_center.asp",
            "link": "",
            "md5": "0c092b679cb8f4ad7da357b709b84686",
            "name": "center",
            "tags": "辅助 工具",
            "tar_url": "center/center.tar.gz",
            "title": "软件中心一键切换",
            "version": "2.0"
        },
        {
            "author": "sadog",
            "build_date": "2021-11-24_11:01:11",
            "changelog": "",
            "description": "CloudFlare DDNS",
            "home_url": "Module_cfddns.asp",
            "link": "",
            "md5": "d101f1ea3dd21633480549cbe10f35f2",
            "name": "cfddns",
            "tags": "DDNS",
            "tar_url": "cfddns/cfddns.tar.gz",
            "title": "CloudFlare DDNS",
            "version": "1.1"
        },
        {
            "author": "sadog",
            "build_date": "2025-11-02_23:47:47",
            "changelog": "",
            "description": "CFE工具箱，查看CFE信息，改机器为国区",
            "home_url": "Module_cfetool.asp",
            "link": "",
            "md5": "66c7405996f61d27430e7dd381f6d5cc",
            "name": "cfetool",
            "port": "8083",
            "server": "42.192.18.234",
            "tags": "系统 工具",
            "tar_url": "cfetool/cfetool.tar.gz",
            "title": "CFE工具箱",
            "version": "4.6"
        },
        {
            "author": "freexiaoyao",
            "build_date": "2023-03-25_00:03:18",
            "changelog": "",
            "description": "ddnspod",
            "home_url": "Module_ddnspod.asp",
            "link": "",
            "md5": "c593de776cc58887a3ca3e243c2d38c8",
            "name": "ddnspod",
            "tags": "DDNS",
            "tar_url": "ddnspod/ddnspod.tar.gz",
            "title": "ddnspod",
            "version": "1.7"
        },
        {
            "author": "xiaobao",
            "build_date": "2022-07-19_15:44:42",
            "changelog": "",
            "description": "ddnsto内网穿透",
            "home_url": "Module_ddnsto.asp",
            "link": "https://www.ddnsto.com",
            "md5": "3c3bd23d7ed6e68b9fadb437baf6398f",
            "name": "ddnsto",
            "tags": "穿透 DDNS",
            "tar_url": "ddnsto/ddnsto.tar.gz",
            "title": "ddnsto",
            "version": "3.0.3"
        },
        {
            "author": "xiaobao",
            "build_date": "2025-07-12_13:41:53",
            "changelog": "",
            "description": "轻量版Docker",
            "home_url": "Module_dockroot.asp",
            "link": "https://www.asusgo.com",
            "md5": "9289680ac49a8c09497f883757bae066",
            "name": "dockroot",
            "tags": "系统",
            "tar_url": "dockroot/dockroot.tar.gz",
            "title": "dockroot",
            "version": "1.20.0"
        },
        {
            "author": "sadog",
            "build_date": "2025-02-19_09:46:25",
            "changelog": "",
            "description": "轻松安装/管理Entware环境",
            "home_url": "Module_entware.asp",
            "link": "",
            "md5": "25b12868d0a572e260202b05f027de51",
            "name": "entware",
            "tags": "Entware USB",
            "tar_url": "entware/entware.tar.gz",
            "title": "Entware",
            "version": "1.8"
        },
        {
            "author": "sadog",
            "build_date": "2025-12-24_13:06:23",
            "changelog": "",
            "description": "将 TCP 连接伪装为 HTTP/HTTPS 协议（NFQUEUE），用于网络流量混淆",
            "home_url": "Module_fakehttp.asp",
            "link": "https://github.com/MikeWang000000/FakeHTTP",
            "md5": "2251ce54393903b71c9a728a78970637",
            "name": "fakehttp",
            "tags": "网络 工具",
            "tar_url": "fakehttp/fakehttp.tar.gz",
            "title": "FakeHTTP 伪装",
            "version": "1.4"
        },
        {
            "author": "sadog",
            "build_date": "2025-12-23_23:23:02",
            "changelog": "",
            "description": "将 UDP 流量伪装为 SIP 协议（NFQUEUE），用于网络流量混淆",
            "home_url": "Module_fakesip.asp",
            "link": "https://github.com/MikeWang000000/FakeSIP",
            "md5": "59c18062a2f116f857ddb67d0b6236c6",
            "name": "fakesip",
            "tags": "网络 工具",
            "tar_url": "fakesip/fakesip.tar.gz",
            "title": "FakeSIP 伪装",
            "version": "1.1"
        },
        {
            "author": "sadog",
            "build_date": "2021-08-20_22:31:28",
            "changelog": "",
            "description": "迅雷快鸟，上网必备神器",
            "home_url": "Module_fastd1ck.asp",
            "link": "",
            "md5": "d2bf4e4cfb6080cdac230a01c19f3d21",
            "name": "fastd1ck",
            "tags": "网络",
            "tar_url": "fastd1ck/fastd1ck.tar.gz",
            "title": "迅雷快鸟",
            "version": "1.6"
        },
        {
            "author": "sadog",
            "build_date": "2025-02-18_15:13:02",
            "changelog": "",
            "description": "检测软件中心重要文件是否被篡改，如果检测到恶意篡改，将其修复",
            "home_url": "Module_fixit.asp",
            "link": "",
            "md5": "823a230f2829c667d0a12c74489b0d9b",
            "name": "fixit",
            "tags": "系统 工具",
            "tar_url": "fixit/fixit.tar.gz",
            "title": "安全检查",
            "version": "1.5"
        },
        {
            "author": "xiaobao",
            "build_date": "2025-05-29_15:28:00",
            "changelog": "",
            "description": "浮动网关",
            "home_url": "Module_floatip.asp",
            "link": "https://www.asusgo.com",
            "md5": "",
            "name": "floatip",
            "tags": "网络",
            "tar_url": "floatip/floatip.tar.gz",
            "title": "floatip",
            "version": "1.0.9"
        },
        {
            "author": "clang",
            "build_date": "2025-12-28_20:05:41",
            "changelog": "",
            "description": "支持多种协议的内网穿透软件",
            "home_url": "Module_frpc.asp",
            "link": "https://github.com/fatedier/frp",
            "md5": "883dfeea83630f37c832f577001bb8b7",
            "name": "frpc",
            "tags": "网络 穿透",
            "tar_url": "frpc/frpc.tar.gz",
            "title": "frpc内网穿透",
            "version": "2.4"
        },
        {
            "author": "clang",
            "build_date": "2025-12-24_00:34:19",
            "changelog": "",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frps.asp",
            "link": "https://github.com/fatedier/frp",
            "md5": "a12235e55e9535b4ec68b69736608c22",
            "name": "frps",
            "tags": "网络 穿透",
            "tar_url": "frps/frps.tar.gz",
            "title": "frps穿透服务器",
            "version": "2.0"
        },
        {
            "author": "sadog",
            "build_date": "2025-12-28_11:22:39",
            "changelog": "",
            "description": "使用此插件可以让你的网络轻松变为Full Cone（全锥形）即NAT1",
            "home_url": "Module_fullcone.asp",
            "link": "",
            "md5": "7e80518a37e2e296da0cfddc696d8695",
            "name": "fullcone",
            "port": "8083",
            "server": "42.192.18.234",
            "tags": "系统 工具",
            "tar_url": "fullcone/fullcone.tar.gz",
            "title": "Fullcone NAT",
            "version": "1.1.2"
        },
        {
            "author": "sadog",
            "build_date": "2025-12-19_15:02:51",
            "changelog": "",
            "description": "本机NAT类型检测工具，测得你路由网络的NAT类型上限",
            "home_url": "Module_gostun.asp",
            "link": "https://github.com/oneclickvirt/gostun",
            "md5": "69f25f5b2c6fd43e44a80f67018e33d9",
            "name": "gostun",
            "tags": "网络 工具",
            "tar_url": "gostun/gostun.tar.gz",
            "title": "Gostun NAT检测",
            "version": "1.1"
        },
        {
            "author": "xiaobao",
            "build_date": "2025-07-10_15:54:49",
            "changelog": "",
            "description": "HomeAssistant智能家居，统一管理以及编排你的家庭智能设备，让生活更智慧。",
            "home_url": "Module_homeassistant.asp",
            "link": "https://www.home-assistant.io/",
            "md5": "0ec96587ed81b6aa022fd5d251c864c0",
            "name": "homeassistant",
            "tags": "工具",
            "tar_url": "homeassistant/homeassistant.tar.gz",
            "title": "HA智能家居",
            "version": "1.1.4"
        },
        {
            "author": "anonymous",
            "build_date": "2021-08-22_16:09:01",
            "changelog": "",
            "description": "kms",
            "home_url": "Module_kms.asp",
            "link": "",
            "md5": "b2c24ae594c9566bcca2fa3a1606e19f",
            "name": "kms",
            "tags": "辅助 工具",
            "tar_url": "kms/kms.tar.gz",
            "title": "系统工具",
            "version": "1.6"
        },
        {
            "author": "xiaobao crwnet",
            "build_date": "2021-08-20_22:31:29",
            "changelog": "",
            "description": "KP: Kids Protect，互联网内容过滤，保护未成年人上网~",
            "home_url": "Module_koolproxy.asp",
            "link": "",
            "md5": "432ce18857a24f170b07b0387ed6771e",
            "name": "koolproxy",
            "tags": "网络 安全",
            "tar_url": "koolproxy/koolproxy.tar.gz",
            "title": "KidsProtect",
            "version": "3.8.4.1"
        },
        {
            "author": "sadog",
            "build_date": "2021-08-20_22:31:28",
            "changelog": "",
            "description": "pppoe单线多拨，带宽提升神器！",
            "home_url": "Module_mdial.asp",
            "link": "",
            "md5": "0d357f44fc5fb9657d8e9187381b6a69",
            "name": "mdial",
            "tags": "网络",
            "tar_url": "mdial/mdial.tar.gz",
            "title": "单线多拨",
            "version": "1.3"
        },
        {
            "author": "sadog",
            "build_date": "2025-12-23_15:51:59",
            "changelog": "",
            "description": "NAT1 打洞端口映射工具，支持TCP/UDP，多任务管理",
            "home_url": "Module_natmap.asp",
            "link": "https://github.com/heiher/natmap",
            "md5": "0ecf806932dd143b2980beeb9293ebf9",
            "name": "natmap",
            "tags": "网络 工具",
            "tar_url": "natmap/natmap.tar.gz",
            "title": "NATMap 端口映射",
            "version": "0.2"
        },
        {
            "author": "sadog",
            "build_date": "2022-01-13_09:31:16",
            "changelog": "",
            "description": "帮助RAX80刷回网件原厂固件，修复RAX80网件原厂分区",
            "home_url": "Module_ngfix.asp",
            "link": "",
            "md5": "0b18ac0f45c1a0ec8f971c4fc6518af8",
            "name": "ngfix",
            "tags": "系统 工具",
            "tar_url": "ngfix/ngfix.tar.gz",
            "title": "RAX80 Toolbox",
            "version": "1.9"
        },
        {
            "author": "sadog",
            "build_date": "2025-02-19_23:16:14",
            "changelog": "",
            "description": "Node.js",
            "home_url": "Module_nodejs.asp",
            "link": "",
            "md5": "003ac5ba59157cf86669972d6a2e9903",
            "name": "nodejs",
            "tags": "Entware",
            "tar_url": "nodejs/nodejs.tar.gz",
            "title": "Node.js",
            "version": "1.6"
        },
        {
            "author": "sadog",
            "build_date": "2025-06-12_16:22:18",
            "changelog": "",
            "description": "让AX86U实现160MHz频宽",
            "home_url": "Module_onesixty.asp",
            "link": "",
            "md5": "bebd02063b9dfbeb768a107ce96edd87",
            "name": "onesixty",
            "tags": "系统 工具",
            "tar_url": "onesixty/onesixty.tar.gz",
            "title": "RT-AX86U 160MHz",
            "version": "1.0"
        },
        {
            "author": "囍冯总囍",
            "build_date": "2022-03-03_14:10:21",
            "changelog": "",
            "description": "通过pushplus将路由器状态推送到微信上",
            "home_url": "Module_pushplus.asp",
            "link": "",
            "md5": "21bfc84132a7e45719bdf974a28dfd31",
            "name": "pushplus",
            "tags": "推送",
            "tar_url": "pushplus/pushplus.tar.gz",
            "title": "pushplus全能推送",
            "version": "0.5"
        },
        {
            "author": "Carseason",
            "build_date": "2021-08-20_22:31:28",
            "changelog": "",
            "description": "自动签到",
            "home_url": "Module_qiandao.asp",
            "link": "",
            "md5": "28e88564762292427836c3679d72add3",
            "name": "qiandao",
            "tags": "签到",
            "tar_url": "qiandao/qiandao.tar.gz",
            "title": "自动签到",
            "version": "1.5"
        },
        {
            "author": "Lonlykids",
            "build_date": "2021-08-20_22:31:30",
            "changelog": "",
            "description": "解决重启Bug",
            "home_url": "Module_reboothelper.asp",
            "link": "https://koolshare.cn/thread-167906-1-1.html",
            "md5": "afe2c55f023cd35cb1681eaefc89a6b8",
            "name": "reboothelper",
            "tags": "系统 工具",
            "tar_url": "reboothelper/reboothelper.tar.gz",
            "title": "重启助手",
            "version": "0.6"
        },
        {
            "author": "sadog",
            "build_date": "2025-11-26_01:15:19",
            "changelog": "",
            "description": "一些小功能的插件",
            "home_url": "Module_rog.asp",
            "link": "",
            "md5": "e1ae0494fa6a3b42d5b4da3de1cf521f",
            "name": "rog",
            "tags": "系统 工具",
            "tar_url": "rog/rog.tar.gz",
            "title": "ROG工具箱",
            "version": "5.9.14"
        },
        {
            "author": "囍冯总囍",
            "build_date": "2021-08-20_22:31:28",
            "changelog": "",
            "description": "从路由器推送状态及通知的工具",
            "home_url": "Module_routerhook.asp",
            "link": "https://koolshare.cn/thread-178114-1-1.html",
            "md5": "b5e09aaf317f20b53d27430bf5894e3d",
            "name": "routerhook",
            "tags": "推送",
            "tar_url": "routerhook/routerhook.tar.gz",
            "title": "RouterHook事件回调",
            "version": "1.2"
        },
        {
            "author": "clang",
            "build_date": "2021-08-20_22:31:26",
            "changelog": "",
            "description": "从路由器推送状态及通知的工具",
            "home_url": "Module_serverchan.asp",
            "link": "",
            "md5": "1a31029f482273a8ead2102084228d4d",
            "name": "serverchan",
            "tags": "推送",
            "tar_url": "serverchan/serverchan.tar.gz",
            "title": "serverChan微信推送",
            "version": "1.4.1"
        },
        {
            "author": "sadog",
            "build_date": "2025-02-19_01:12:33",
            "changelog": "",
            "description": "Sftp Server",
            "home_url": "Module_sftpserver.asp",
            "link": "",
            "md5": "be810fca7662716287d144ece5515117",
            "name": "sftpserver",
            "tags": "Entware",
            "tar_url": "sftpserver/sftpserver.tar.gz",
            "title": "Sftp Server",
            "version": "1.4"
        },
        {
            "author": "sadog",
            "build_date": "2021-08-20_22:31:26",
            "changelog": "",
            "description": "超强的SSH网页客户端~",
            "home_url": "Module_shellinabox.asp",
            "link": "",
            "md5": "98e0a209ad46081c6578169bd8e28df5",
            "name": "shellinabox",
            "tags": "系统 工具",
            "tar_url": "shellinabox/shellinabox.tar.gz",
            "title": "shellinabox",
            "version": "1.6"
        },
        {
            "author": "sadog",
            "build_date": "2021-08-20_22:31:26",
            "changelog": "",
            "description": "上海电信IPTV，4K IPTV 一键开启",
            "home_url": "Module_shiptv.asp",
            "link": "",
            "md5": "bb6c6a612e2e195292c5338c5f374af7",
            "name": "shiptv",
            "tags": "网络",
            "tar_url": "shiptv/shiptv.tar.gz",
            "title": "上海电信IPTV",
            "version": "1.1"
        },
        {
            "author": "sadog",
            "build_date": "2021-08-20_22:31:27",
            "changelog": "",
            "description": "VPN全家桶, ver 4.29 build 9680",
            "home_url": "Module_softether.asp",
            "link": "",
            "md5": "e9ef5223ff1dab00e2ab8cb60a3f9f69",
            "name": "softether",
            "tags": "网络 VPN",
            "tar_url": "softether/softether.tar.gz",
            "title": "SoftEther_VPN_Server",
            "version": "1.9"
        },
        {
            "author": "sadog",
            "build_date": "2021-08-20_22:31:30",
            "changelog": "",
            "description": "让路由器运行更稳定~",
            "home_url": "Module_swap.asp",
            "link": "",
            "md5": "1f276efccd32f6a0a81f0eea9b966471",
            "name": "swap",
            "tags": "USB",
            "tar_url": "swap/swap.tar.gz",
            "title": "虚拟内存",
            "version": "2.7"
        },
        {
            "author": "sadog",
            "build_date": "2025-02-18_15:55:40",
            "changelog": "",
            "description": "基于wiregurad协议的零配置内网穿透安全组网工具！",
            "home_url": "Module_tailscale.asp",
            "link": "",
            "md5": "c7efd35f8679668af4189f80b38c1a0a",
            "name": "tailscale",
            "tags": "穿透 VPN",
            "tar_url": "tailscale/tailscale.tar.gz",
            "title": "Tailscale",
            "version": "2.0.3"
        },
        {
            "author": "sadog",
            "build_date": "2025-11-02_21:55:43",
            "changelog": "",
            "description": "tmux是一个终端复用器,它可以启动一系列终端会话。",
            "home_url": "Module_tmux.asp",
            "link": "",
            "md5": "39c882abef265cf99a6fe8b3df927870",
            "name": "tmux",
            "tags": "Entware",
            "tar_url": "tmux/tmux.tar.gz",
            "title": "tmux",
            "version": "1.2"
        },
        {
            "author": "sadog",
            "build_date": "2023-08-02_11:44:40",
            "changelog": "",
            "description": "使用U盘轻松挂载jffs",
            "home_url": "Module_usb2jffs.asp",
            "link": "",
            "md5": "f2a9e7d69949a5d89cefbbe1410ad9be",
            "name": "usb2jffs",
            "tags": "USB",
            "tar_url": "usb2jffs/usb2jffs.tar.gz",
            "title": "USB2JFFS",
            "version": "2.1.6"
        },
        {
            "author": "sadog",
            "build_date": "2025-11-11_23:41:34",
            "changelog": "",
            "description": "wifi boost: 路由器WiFi功率增强，增加信号覆盖范围。",
            "home_url": "Module_wifiboost.asp",
            "link": "",
            "md5": "d0e309856698a27c42e9bddf39c6e36d",
            "name": "wifiboost",
            "port": "8083",
            "server": "42.192.18.234",
            "tags": "系统 工具",
            "tar_url": "wifiboost/wifiboost.tar.gz",
            "title": "wifi boost",
            "version": "4.9.11"
        },
        {
            "author": "sadog",
            "build_date": "2025-11-02_21:31:55",
            "changelog": "",
            "description": "ZeroTier 内网穿透",
            "home_url": "Module_zerotier.asp",
            "link": "",
            "md5": "20b5c0f6ab12a0378573e4a6967d61a3",
            "name": "zerotier",
            "tags": "穿透 VPN",
            "tar_url": "zerotier/zerotier.tar.gz",
            "title": "ZeroTier",
            "version": "1.5.2"
        }
    ],
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master",
    "md5": "e2b4fc6df489563681ec93fb3d19bada",
    "tar_url": "koolcenter/softcenter.tar.gz",
    "version": "1.9.52"
}