{
    "apps": [
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "link": "https://github.com/acmesh-official/acme.sh", 
            "md5": "1020c8b26b21a57b23338e32301fb197", 
            "name": "acme", 
            "tags": "网络 工具", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.3"
        }, 
        {
            "author": "kyrios, sadog", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "link": "", 
            "md5": "7c769ec774775d74f396ed900eae5b27", 
            "name": "aliddns", 
            "tags": "网络 DDNS", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.1"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "link": "", 
            "md5": "daac62b77337865503801b0b87c64ad8", 
            "name": "aria2", 
            "tags": "下载 USB", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "aria2", 
            "version": "2.2"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:17", 
            "changelog": "", 
            "description": "CloudFlare DDNS", 
            "home_url": "Module_cfddns.asp", 
            "link": "", 
            "md5": "fca779ad02125888d6011c037849bdfb", 
            "name": "cfddns", 
            "tags": "网络 DDNS", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "CloudFlare DDNS", 
            "version": "1.0"
        }, 
        {
            "author": "freexiaoyao", 
            "build_date": "2021-08-05_21:06:19", 
            "changelog": "", 
            "description": "ddnspod", 
            "home_url": "Module_ddnspod.asp", 
            "link": "", 
            "md5": "c3e7a5098da11df011f8892def5b53a6", 
            "name": "ddnspod", 
            "tags": "网络 DDNS", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "ddnspod", 
            "version": "1.5"
        }, 
        {
            "author": "xiaobao", 
            "build_date": "2021-08-05_21:06:19", 
            "changelog": "", 
            "description": "ddnsto内网穿透", 
            "home_url": "Module_ddnsto.asp", 
            "link": "https://www.ddnsto.com", 
            "md5": "486edf1736ef9d69534a6209a0fd32a3", 
            "name": "ddnsto", 
            "tags": "内网穿透 DDNS", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "ddnsto", 
            "version": "2.2"
        }, 
        {
            "author": "xiaobao", 
            "build_date": "2021-08-05_21:06:17", 
            "changelog": "", 
            "description": "易有云 （EasyExplorer） 跨平台文件同步，支持双向同步！", 
            "home_url": "Module_easyexplorer.asp", 
            "link": "", 
            "md5": "b94f3dd1a07339f412f8181a721181a7", 
            "name": "easyexplorer", 
            "tags": "云同步 USB", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "易有云", 
            "version": "2.4.1"
        }, 
        {
            "author": "", 
            "build_date": "2021-08-08_13:26:53", 
            "changelog": "", 
            "description": "轻松安装/管理Entware环境", 
            "home_url": "Module_entware.asp", 
            "link": "", 
            "md5": "46127d5ad847968eab5d3b972a58c915", 
            "name": "entware", 
            "tags": "其它", 
            "tar_url": "entware/entware.tar.gz", 
            "title": "Entware", 
            "version": "1.2"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "迅雷快鸟，上网必备神器", 
            "home_url": "Module_fastd1ck.asp", 
            "link": "", 
            "md5": "9703ad4970b665e39666d201f659cae8", 
            "name": "fastd1ck", 
            "tags": "网络 工具", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "1.6"
        }, 
        {
            "author": "clang", 
            "build_date": "2021-08-05_21:06:17", 
            "changelog": "", 
            "description": "支持多种协议的内网穿透软件", 
            "home_url": "Module_frpc.asp", 
            "link": "", 
            "md5": "7b5f22c2678ca33c8fdef06b0a23fe7f", 
            "name": "frpc", 
            "tags": "内网穿透 DDNS", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc内网穿透", 
            "version": "1.7"
        }, 
        {
            "author": "clang", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "link": "", 
            "md5": "a50806415e3d615822b91518a56c26d5", 
            "name": "frps", 
            "tags": "内网穿透 DDNS", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "1.5.2"
        }, 
        {
            "author": "", 
            "build_date": "2021-08-05_21:06:17", 
            "changelog": "", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "link": "", 
            "md5": "de1e45904cc7c0959a3143ad253e7097", 
            "name": "kms", 
            "tags": "辅助 工具", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "1.6"
        }, 
        {
            "author": "xiaobao crwnet", 
            "build_date": "2021-08-05_21:06:19", 
            "changelog": "", 
            "description": "KP: Kids Protect，互联网内容过滤，保护未成年人上网~", 
            "home_url": "Module_koolproxy.asp", 
            "link": "", 
            "md5": "9059277d4bd4acfb2aaea2ac6d9576b5", 
            "name": "koolproxy", 
            "tags": "网络 工具", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "KidsProtect", 
            "version": "3.8.4.1"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "link": "", 
            "md5": "c6e123d87401f5f41cc4df4447678efc", 
            "name": "mdial", 
            "tags": "网络 工具", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.3"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "帮助RAX80刷回网件原厂固件，修复RAX80网件原厂分区", 
            "home_url": "Module_ngfix.asp", 
            "link": "", 
            "md5": "d0905c6128a92ae8df96b68def100605", 
            "name": "ngfix", 
            "tags": "系统 工具", 
            "tar_url": "ngfix/ngfix.tar.gz", 
            "title": "RAX80 Toolbox", 
            "version": "1.8"
        }, 
        {
            "author": "", 
            "build_date": "2021-08-08_13:10:42", 
            "changelog": "", 
            "description": "Node.js", 
            "home_url": "Module_nodejs.asp", 
            "link": "", 
            "md5": "e3ba14afa01d3cd53db290520d1feb91", 
            "name": "nodejs", 
            "tags": "其它", 
            "tar_url": "nodejs/nodejs.tar.gz", 
            "title": "Node.js", 
            "version": "1.1"
        }, 
        {
            "author": "囍冯总囍", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "通过pushplus将路由器状态推送到微信上", 
            "home_url": "Module_pushplus.asp", 
            "link": "", 
            "md5": "79e5f5fb8fe7847742f5ef33a712e4e0", 
            "name": "pushplus", 
            "tags": "推送", 
            "tar_url": "pushplus/pushplus.tar.gz", 
            "title": "pushplus全能推送", 
            "version": "0.4"
        }, 
        {
            "author": "Carseason", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "自动签到", 
            "home_url": "Module_qiandao.asp", 
            "link": "", 
            "md5": "5d15e3ea7d1421cfe4a0071b74382ff3", 
            "name": "qiandao", 
            "tags": "签到", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "自动签到", 
            "version": "1.5"
        }, 
        {
            "author": "Lonlykids", 
            "build_date": "2021-08-05_21:06:19", 
            "changelog": "", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "link": "https://koolshare.cn/thread-167906-1-1.html", 
            "md5": "34ec5beea19708aec1cbc106d09decae", 
            "name": "reboothelper", 
            "tags": "系统 工具", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.6"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-08_10:13:03", 
            "changelog": "", 
            "description": "一些小功能的插件", 
            "home_url": "Module_rog.asp", 
            "link": "https://koolshare.cn/thread-179110-1-5.html", 
            "md5": "075d8a7fc4cfe43d5525dc0baf14d8b6", 
            "name": "rog", 
            "tags": "系统 工具", 
            "tar_url": "rog/rog.tar.gz", 
            "title": "ROG工具箱", 
            "version": "4.3"
        }, 
        {
            "author": "囍冯总囍", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_routerhook.asp", 
            "link": "https://koolshare.cn/thread-178114-1-1.html", 
            "md5": "c5f0aa890023b62c7954f7bb417c74ac", 
            "name": "routerhook", 
            "tags": "通知", 
            "tar_url": "routerhook/routerhook.tar.gz", 
            "title": "RouterHook事件回调", 
            "version": "1.2"
        }, 
        {
            "author": "clang", 
            "build_date": "2021-08-05_21:06:17", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "link": "", 
            "md5": "d7f9e4142f92263b1f9b99589d282e52", 
            "name": "serverchan", 
            "tags": "通知", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "serverChan微信推送", 
            "version": "1.4.1"
        }, 
        {
            "author": "", 
            "build_date": "2021-08-11_11:11:43", 
            "changelog": "", 
            "description": "Sftp Server", 
            "home_url": "Module_sftpserver.asp", 
            "link": "", 
            "md5": "4e1934f1481f28449ba58bea7bb9fbbb", 
            "name": "sftpserver", 
            "tags": "其它", 
            "tar_url": "sftpserver/sftpserver.tar.gz", 
            "title": "Sftp Server", 
            "version": "1.2"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:17", 
            "changelog": "", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "link": "", 
            "md5": "33afebf42aec3f524637cae4dc14f88c", 
            "name": "shellinabox", 
            "tags": "系统 工具", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "1.6"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:17", 
            "changelog": "", 
            "description": "上海电信IPTV，4K IPTV 一键开启", 
            "home_url": "Module_shiptv.asp", 
            "link": "", 
            "md5": "009698756d133a714156e777be4875e1", 
            "name": "shiptv", 
            "tags": "网络 工具", 
            "tar_url": "shiptv/shiptv.tar.gz", 
            "title": "上海电信IPTV", 
            "version": "1.1"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:17", 
            "changelog": "", 
            "description": "VPN全家桶, ver 4.29 build 9680", 
            "home_url": "Module_softether.asp", 
            "link": "", 
            "md5": "4244be7fc236f3a3a7cb811e6279f806", 
            "name": "softether", 
            "tags": "网络 VPN", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "1.9"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:19", 
            "changelog": "", 
            "description": "让路由器运行更稳定~", 
            "home_url": "Module_swap.asp", 
            "link": "", 
            "md5": "31f6b43c91ba53863c8f509627ce384b", 
            "name": "swap", 
            "tags": "工具 USB", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.7"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:18", 
            "changelog": "", 
            "description": "使用U盘轻松挂载jffs", 
            "home_url": "Module_usb2jffs.asp", 
            "link": "", 
            "md5": "008a33d4eed2153f2236b73a934f76e0", 
            "name": "usb2jffs", 
            "tags": "工具 USB", 
            "tar_url": "usb2jffs/usb2jffs.tar.gz", 
            "title": "USB2JFFS", 
            "version": "1.9.8"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-08_23:52:13", 
            "changelog": "", 
            "description": "wifi boost: 路由器WiFi功率增强，增加信号覆盖范围。", 
            "home_url": "Module_wifiboost.asp", 
            "link": "", 
            "md5": "ba8a8e48698c26e555ae0372b3947d7f", 
            "name": "wifiboost", 
            "port": "8083", 
            "server": "42.192.18.234", 
            "tags": "系统 工具", 
            "tar_url": "wifiboost/wifiboost.tar.gz", 
            "title": "wifi boost", 
            "version": "4.1"
        }, 
        {
            "author": "sadog", 
            "build_date": "2021-08-05_21:06:19", 
            "changelog": "", 
            "description": "ZeroTier 内网穿透", 
            "home_url": "Module_zerotier.asp", 
            "link": "", 
            "md5": "da5c568d13ea19b5b2c7cfe39ec2bd9e", 
            "name": "zerotier", 
            "tags": "内网穿透 VPN", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "ZeroTier", 
            "version": "1.3.8"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "82f5365eaf65032ac709a8ac2c7b2b6c", 
    "tar_url": "koolcenter/softcenter.tar.gz", 
    "version": "1.9.0.4"
}